name: CI/CD Pipeline

on:
  push:
    branches:
      - main  

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t prasanna2703/sample-app:latest .

    - name: Push Docker image to Docker Hub
      run: |
        docker push prasanna2703/sample-app:latest

    - name: Deploy Docker container to EC2
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@18.201.238.100 << 'EOF'
        docker pull prasanna2703/sample-app:latest
        docker run -d -p 3000:3000 prasanna2703/sample-app:latest
        EOF
